### ISSUE TITLE
"TypeError: e is not iterable" when running action

### ISSUE THREAD

**Issue by terrymun** [ScaCap/code-coverage-assistant#48]
When attempting to run the GitHub action with the barebones config for a monorepo:

```yml
- name: Add coverage comment
        uses: ScaCap/code-coverage-assistant@v1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          monorepo-base-path: './packages'
```

I get the following error:

```
TypeError: e is not iterable
```

I suspect it is because the action is unable to locate the appropriate `lcov.info`? All coverage files are actually not created in `<ROOT>/packages`, but into `<ROOT>/coverage/packages`. Changing the `monorepo-base-path` to `./coverage/packages` throws a different error:

```
Failed to parse string
```
